### ISSUE TITLE
[FEAT] UX, UI 개선

### ISSUE THREAD

**Issue by sarumi-k** [sareum-k/payhere#11]
### Description
- UX, UI 개선 부분 고민 후 적용하기

### Todo
- [x] 로딩에 대한 개선
- [x] 페이지네이션에 대한 개선
- [ ] 유저가 클릭한 사항에 대한 안내 추가 필요 여부
