### ISSUE TITLE
[FEAT] README 작성하기

### ISSUE THREAD

**Issue by sarumi-k** [sareum-k/payhere#12]
### Description
- 제출 하루 전까지 README 작성하기

### Todo
- [x] gif 작업
- [x] 구현 사항 작성
- [x] 렌더링 최적화
- [x] UX/UI 개선 사항
- [ ] dev_log 작성
- [x] 배포링크
- [x] 설치 및 실행 방법
- [x] 폴더 구조
